[package]
name = "webrender_traits"
version = "0.2.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]
build = "build.rs"

[features]
default = ["serde_codegen"]
nightly = ["euclid/unstable", "serde/nightly"]

[dependencies.ipc-channel]
git = "https://github.com/servo/ipc-channel"

[dependencies]
app_units = "0.2.5"
byteorder = "0.5"
euclid = "0.7.1"
gleam = "0.2.19"
heapsize = "0.3.6"
offscreen_gl_context = {version = "0.1.9", features = ["serde_serialization"]}
serde = "0.7.11"
serde_macros = {version = "0.7.11", optional = true}
uuid = {version = "0.2", features = ["v4"]}

[target.x86_64-apple-darwin.dependencies]
core-graphics = ">=0.2, <0.4"

[build-dependencies]
serde_codegen = {version = "0.7.11", optional = true}
